config/routes.rb
GxfWebsite::Application.routes.draw do
  

  mount RedactorRails::Engine => '/redactor_rails'

  # resources :posts, only: [:index, :show]
  

 
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 
  resources :sessions
  

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :posts
    resources :users
    resources :pages
  end


  root :to => 'site#index'

  match '/blog' => 'posts#index', as: :posts
  match '/blog/:id' => 'posts#show', as: :post #_permalink
  # get 'posts\:id', to: 'posts#show', as: :post
  get ':id', to: 'pages#show', as: :page
end

app/views/admin/pages/_form.html.erb
<%= form_for([:admin, @page]) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field" id="permalinkPreview">
    <label>Permalink:</label><p id="pre"></p>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
$(function(){
    var currentValue, permalink, domain;
    
    //grabs the windows current location
    domain = window.location.origin;

    // sets the permalink preview on pageload & updates on changes
    function makePermalink(){
      permalink = $('#page_name').val().trim();
      permalink = permalink.toLowerCase();
      permalink = permalink.replace(/ /g, '-');
      $('#permalinkPreview #pre').html(domain + '/' + permalink);
    }

    // Set the permalink preview on load
    makePermalink();

    // listens for change event to update the permalink preview
    // It was keyup(). but couldnt use autocomplete.
    $('#page_name').change(function(){
        makePermalink();
        

    });          
  

});
</script>

app/views/admin/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_page_path(@page) %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<%= title 'Admin - Manage Pages' %>
  <span class="left inline"><h3>Manage Pages</h3></span>
  <ul class="button-group right">
    <li><%= link_to glyph_helper('z') + ' New Page', new_admin_page_path, class: 'radius button ' %></li>
  </ul>  

    
<section class="pages">
  <table>
    <thead>
      <th>Name</th>
      <th>Permalink</th>
      <th>Updated At</th>
     
      <th></th>
      
    </thead>

  <% @pages.each do |page| %>
    <tr>
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td><%= page.updated_at.strftime('%D') %></td>
      <td>
        <ul class="button-group radius">

          <li> 
            <%= link_to link_to glyph_helper('k') + 'Edit', edit_admin_page_path(page), class: 'button success radius small' %>
          </li>
          <li><%= link_to link_to glyph_helper('g') + 'Delete', admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button radius alert small' %></li>
        </ul>
      </td>
      
    </tr>
  <% end %>
  </table>

</section>

app/views/admin/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/admin/pages/show.html.erb
<p>
  <b>Name:</b>
  <%= @page.name %>
</p>

<p>
  <b>Permalink:</b>
  <input type="text" id="permalinkPreview">
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>