config/routes.rb
GxfWebsite::Application.routes.draw do
  

  mount RedactorRails::Engine => '/redactor_rails'

  # resources :posts, only: [:index, :show]
  

 
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 
  resources :sessions
  

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :posts
    resources :users
    resources :pages
  end


  root :to => 'site#index'

  match '/blog' => 'posts#index', as: :posts
  match '/blog/:id' => 'posts#show', as: :post #_permalink
  # get 'posts\:id', to: 'posts#show', as: :post
  get ':id', to: 'pages#show', as: :page
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :published, :title, :permalink

  validates_uniqueness_of :permalink, :title
  validates_presence_of :title

  scope :pub, where(published: true).order('created_at DESC')

  before_create do |post|
    post.permalink = post.title.slugify
  end


  def to_param
    permalink
  end
    
   

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_filter :authorize

  layout 'admin'
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_permalink!(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find_by_permalink!(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_posts_url, 
          notice: 'Post was successfully created.' }
        format.json { render json: @post, 
          status: :created,
          location: [:admin, @post] }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, 
          status: :unprocessable_entity }
      end
    end


  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find_by_permalink!(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to admin_posts_url, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find_by_permalink!(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_posts_url, alert: 'Post was deleted!.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  respond_to :html, :json

  def index
    @posts = Post.pub.paginate( page: params[:page], per_page: 1)
    respond_with @posts

  end

  def show
    @post = Post.pub.find_by_permalink!(params[:id])
    respond_with @post
  end


  

end

app/helpers/posts_helper.rb
module PostsHelper

  def status
    if self.published 
      raw "<span class='success label'>Published</span>"
    else
      raw "<span class='secondary label'>Draft</span>"
    end
  end 
  
  
end

app/views/admin/posts/_form.html.erb
<%= form_for([:admin, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.text_field :title, placeholder: '( Post title )' %>
  </div>
  <div class="field">
    <%= f.text_area :body, class: 'redactor', rows: 40, cols: 120 %>
  </div>
  <div class="field">
    <%= f.label :published  %>
    <%= f.check_box :published %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/posts/_post_status.html.erb
<% if post.published %>
  <span class='label'>Published</span>
<% else %>
  <span class='secondary label'>Draft</span>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_post_path(@post) %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
  <%= title 'Admin - Manage Posts' %>
  <span class="left inline"><h3>Manage Posts</h3></span>
  <ul class="button-group right">
    <li><%= link_to glyph_helper('z') + ' New Post', new_admin_post_path, class: 'radius button secondary' %></li>
  </ul>  

    
<section class="posts">
  <table>
    <thead>
      <th>Title</th>
      <th>Status</th>
      <th></th>
     
    </thead>

  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, admin_post_path(post) %></td>
      <td>

        <%= render 'admin/posts/post_status', post: post %>

      </td>
      <td>
        <ul class="button-group radius">

          <li> 
            <%= link_to link_to glyph_helper('k') + 'Edit', edit_admin_post_path(post), class: 'button success small' %>
          </li>
          <li><%= link_to link_to glyph_helper('g') + 'Delete', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button alert small' %></li>
        </ul>
      </td>
    </tr>
  <% end %>

  </table>
</section>

app/views/admin/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<strong>PREVIEW OF: <%= @post.title %></strong>
<span class='right'>
  <%= link_to 'Edit', edit_admin_post_path(@post) %> |
  <%= link_to 'Back', admin_posts_path %>
</span>


<h2><%= @post.title %></h2>

<%= raw @post.body %>