config/routes.rb
GxfWebsite::Application.routes.draw do
  

  mount RedactorRails::Engine => '/redactor_rails'

  # resources :posts, only: [:index, :show]
  

 
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 
  resources :sessions
  

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :posts
    resources :users
    resources :pages
  end


  root :to => 'site#index'

  match '/blog' => 'posts#index', as: :posts
  match '/blog/:id' => 'posts#show', as: :post #_permalink
  # get 'posts\:id', to: 'posts#show', as: :post
  get ':id', to: 'pages#show', as: :page
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation
  
  validates_uniqueness_of :email
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorize

  layout 'admin'

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_users_url, 
          notice: 'User was successfully created.' }
        format.json { render json: @user, 
          status: :created,
          location: [:admin, @user] }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, 
          status: :unprocessable_entity }
      end
    end


  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully deleted!' }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<div class="button-bar">
  <ul class="button-group">
    <li><%= link_to glyph_helper('z') + ' New User', new_admin_post_path, class: 'radius button secondary' %></li>
  </ul>  
</div>
<section class="users">
  <table>
    <thead>
      <th >Email</th>
      <th >Created At</th>
      <th></th>
    </thead>

  <% @users.each do |user| %>
    <tr>
      <td><%=  user.email %></td>
     <td><%=  user.created_at.strftime('%d/%m/%y') %></td>
      <td>
        <ul class="button-group even">
          <li><%= link_to glyph_helper('k') + 'Edit', edit_admin_user_path(user), class: 'button secondary small' %></li>
          <li><%= link_to glyph_helper('g') + 'Delete' , admin_user_path(user), class: 'button secondary small', method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </td>
    </tr>
  <% end %>

  </table>

</section>

app/views/admin/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email: <%= @user.email %> </b>
</p>

<%= link_to 'Edit', edit_admin_users_path(@user) %>
<%= link_to 'Back', admin_users_path %>