config/routes.rb
GxfWebsite::Application.routes.draw do
  

  mount RedactorRails::Engine => '/redactor_rails'

  # resources :posts, only: [:index, :show]
  

 
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 
  resources :sessions
  

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :posts
    resources :users
    resources :pages
  end


  root :to => 'site#index'

  match '/blog' => 'posts#index', as: :posts
  match '/blog/:id' => 'posts#show', as: :post #_permalink
  # get 'posts\:id', to: 'posts#show', as: :post
  get ':id', to: 'pages#show', as: :page
end

app/views/layouts/admin-dash.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  
  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <title><%= content_for?(:title) ? yield(:title) : "GoodXFortune.com" %></title>
  
  <!-- Included CSS Files -->
  <%= stylesheet_link_tag    "application" %>
  
  <!-- Included JS Files  -->
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body class="admin">
  <header>
  <div class="container">
    <nav class="top-bar">
      <ul>
        <li class="name">
          <h1> 
            <%= link_to glyph_helper('m'), admin_path %> 
          </h1>
        </li>
      </ul>
      <% if current_user %>
      <section>
        <ul class="right">

          <li> <%= link_to "Log Out", logout_path %></li>
        </ul>
      </section>
      <% end %>
    </nav>
  
  </div>
</header>

  <div class="container">
    <div class="row">

      

      <div id="content" class="twelve columns">
        <%= yield %>
        <%= render 'shared/custom-flash', flash: flash %>

      </div>
       
    </div>   
  </div>

</body>
</html>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  
  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
  
  <!-- Included CSS Files -->
  <%= stylesheet_link_tag    "application" %>
  
  <!-- Included JS Files  -->
  <%= javascript_include_tag "application"%>
  
  <%= csrf_meta_tags %>
</head>
<body class="admin">
  <header>
  <div class="container">
    <nav class="top-bar">
      <ul>
         <li class="name">
          <h1> 
            <%= link_to glyph_helper('m'), admin_path %> 
          </h1>
        </li>
        
      </ul>
      <% if current_user %>
      <section>
        <ul class="right">
          <li> <%= link_to glyph_helper(';') + 'View Site', root_path %> </li>
          <li> <%= link_to "Log Out", logout_path %></li>
        </ul>
      </section>
      <% end %>
    </nav>
  
  </div>
</header>

  <div class="container">
    <div class="row">

      <%= render 'admin/sidebar' %>

      <div id="content" class="nine columns">
        <%= yield %>
        <%= render 'shared/custom-flash' , flash: flash %>

      </div>
       
    </div>   
  </div>


</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
	
	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="root">
		<header>
			<div class="container">
			
				<div class="row">
					<div class="five columns">
						<a href="/"><img src="/assets/logo_header.png" /></a>
					</div>
					<div class="seven columns">
						<nav>
							<%= link_to "blog", posts_path %>
						</nav>
					</div>
				</div>
			
			</div>
		</header>

		<div class="container">
			<div class="row">
	 			 <%= yield %>
 			   <%= render 'shared/custom-flash', flash: flash %>

	 		</div>	 
	  </div>
	  <div id="root_footer"></div>
	</div><!-- end of root (for Compass sticky footer)-->

	<footer class="container" id="footer">
		<div class="row">
			<p>2012 &copy; Good Fortune Clothing. All Rights Reserved.
			
			<span class="right ">
					<% if current_user %>
				    Logged in as <%= current_user.email %>.
				    <%= link_to "Log Out", logout_path, class: 'button secondary small' %>
				  <% else%>
						<%= link_to "Log In", login_path, class: 'button secondary small' %>
					<% end %></span>
			</p>
		</div>
	</footer>
</body>
</html>